SELECT * FROM CLIENTE
SELECT * FROM TIENDA
SELECT * FROM PRODUCTO
SELECT * FROM VENTA
SELECT * FROM CLIENTEPERFIL

ALTER TABLE VENTA ADD Total DECIMAL(10,2)
SELECT * FROM CLIENTE 
SELECT * FROM CLIENTEPERFIL